name: diapalet
description: "QR ile mal kabul ve satış"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.0.0
  path: ^1.8.3
  device_info_plus: ^10.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  collection: ^1.17.2
  path_provider: ^2.1.1
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  provider: ^6.1.2
  easy_localization: ^3.0.5
  sqflite: ^2.3.2
  rxdart: ^0.27.7
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
