name: diapalet
description: "QR ile mal kabul ve satış"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  provider: ^6.1.5
  intl: ^0.20.2
  mobile_scanner: ^7.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^6.0.0
  uuid: ^3.0.7
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
